#!/bin/sh

USERNAME=ruttarchvp
HOST=ftp.cluster023.hosting.ovh.net
PASS=Fuiibi321


echo "Starting to sftp..."


lftp -u ${USERNAME},${PASS} ftp://${HOST}:21 <<EOF
mirror -vnp -P 6 -R -x media -x \.map$  dist www
bye
EOF

echo "done"

